# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title SavGol
#'
#' @export
rcpp_regWSavGol <- function(y, w, halfwin, d) {
    .Call('_phenoRS_rcpp_regWSavGol', PACKAGE = 'phenoRS', y, w, halfwin, d)
}

